apiVersion: v1
kind: Service
metadata:
  name: coworking-analytics-service
spec:
  type: LoadBalancer
  selector:
    app: coworking-analytics
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5153